name: Build and Push Backend

on:
  # Uruchamianie automatyczne (np. po merge do main)
  push:
    branches: [ "main" ]
    
  # Uruchamianie ręczne z poziomu interfejsu (UI) repozytorium frontendowego
  workflow_dispatch:
    inputs:
      custom_commit:
        description: 'Podaj SHA commita (zostaw puste, by zbudować obecny)'
        required: false
        type: string
      push_image:
        description: 'Czy wysłać do GHCR?'
        required: true
        type: boolean
        default: true

jobs:
  call-central-docker-build:
    # Odwołanie do Twojego centralnego repozytorium
    uses: skni-kod/skni-platform-workflows/.github/workflows/docker-build.yaml@main
    with:
      # Jeśli deweloper wpisał własne SHA w workflow_dispatch, używamy go. 
      # W przeciwnym wypadku domyślnie bierzemy SHA commita z kontekstu wywołania.
      commit_id: ${{ github.event.inputs.custom_commit || github.sha }}
      
      # Nazwa wyciągnięta dynamicznie z nazwy obecnego repozytorium (np. iss-model-frontend)
      image_name: ${{ github.event.repository.name }}
      
      # Zostanie nadpisane na false, jeśli deweloper odznaczy checkbox w UI
      push: ${{ github.event.inputs.push_image || true }}
      
      dockerfile_path: 'Dockerfile'
      lint_dockerfile: true
